# Generated by Django 3.0.7 on 2020-06-23 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('hari_waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('agenda', models.CharField(max_length=15)),
                ('tempat', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('hari_waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('tempat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id_peserta', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('tgl_daftar', models.DateTimeField(default=datetime.datetime.now)),
                ('nama', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('tmp_lahir', models.CharField(max_length=10)),
                ('tgl_lahir', models.DateTimeField(default=datetime.datetime.now)),
                ('jenjang', models.CharField(max_length=3)),
                ('no_telp', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=10)),
                ('jadwal_1', models.CharField(max_length=15)),
                ('jadwal_2', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='default.jpg', upload_to='gambar')),
            ],
        ),
    ]
